#!/bin/sh

L=g2ools-
HTDOCSFILES=/v/www/localhost/htdocs/files

rm -rf ~/nord/${L}*
hg clone . ..//${L}$1
echo "version='$1'" >>../${L}$1/nord/convert/version.py
(cd ..;zip -r ${L}$1.zip ${L}$1)
rm ${HTDOCSFILES}/${L}*
cp ~/nord/${L}$1.zip ${HTDOCSFILES}
ls ${HTDOCSFILES}

