#!/bin/sh

if [ $# -lt 1 ]; then
	echo "usage: $0 <version>"
	exit 1
fi

L=g2ools-
V=${L}$1
DEST=/v/www/files

rm -rf ~/nord/${L}*
hg clone . ..//${V}
echo "version='$1'" >>../${V}/nord/convert/version.py
(cd ..;zip -r ${V}.zip ${V})
rm ${DEST}/${L}*
cp -v ~/nord/${V}.zip ${DEST}
ls ${DEST}

