#!/usr/bin/env python2

from nord import printf, Struct
from nord.types import *
from nord.nm1.colors import nm1conncolors

class ParameterDef(Struct):
  pass

class ModuleMap(Struct):
  pass

audio, control, logic, slave = range(4)

modules = [
  ModuleType(
    shortnm='Keyboard',
    id=1,
    height=2,
    inputs=[],
    outputs=[
      OutputType('Note',         nm1conncolors.control),
      OutputType('Gate',         nm1conncolors.logic),
      OutputType('VelocityOn',   nm1conncolors.control),
      OutputType('VelocityRel',  nm1conncolors.control),
    ],
    params=[],
    modes=[],
  ),
  ModuleType(
    shortnm='AudioIn',
    id=2,
    height=2,
    inputs=[],
    outputs=[
      OutputType('Left',         nm1conncolors.audio),
      OutputType('Right',        nm1conncolors.audio),
    ],
    params=[],
    modes=[],
  ),
  ModuleType(
    shortnm='4Output',
    id=3,
    height=3,
    inputs=[
      InputType('Out1',         nm1conncolors.audio),
      InputType('Out2',         nm1conncolors.audio),
      InputType('Out3',         nm1conncolors.audio),
      InputType('Out4',         nm1conncolors.audio),
    ],
    outputs=[],
    params=[
      ParamType('Level',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='2Output',
    id=4,
    height=3,
    inputs=[
      InputType('OutLeft',      nm1conncolors.audio),
      InputType('OutRight',     nm1conncolors.audio),
    ],
    outputs=[],
    params=[
      ParamType('Level',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Destination',
        ParamDef(  default=0, low=0, high=2, comment='2destination'),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='1Output',
    id=5,
    height=3,
    inputs=[
      InputType('Out',          nm1conncolors.audio),
    ],
    outputs=[],
    params=[
      ParamType('Level',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Destination',
        ParamDef(  default=0, low=0, high=5, comment='1destination'),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='OscA',
    id=7,
    height=6,
    inputs=[
      InputType('Sync',         nm1conncolors.audio),
      InputType('FmMod',        nm1conncolors.audio),
      InputType('PitchMod1',    nm1conncolors.audio),
      InputType('PitchMod2',    nm1conncolors.audio),
      InputType('PwMod',        nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
      OutputType('Slv',          nm1conncolors.slave),
    ],
    params=[
      ParamType('FreqCoarse',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('FreqFine',
        ParamDef(  default=0, low=0, high=127, comment='freqfine'),
      ),
      ParamType('Kbt',
        ParamDef(  default=0, low=0, high=127, comment='freqkbt'),
      ),
      ParamType('PulseWidth',
        ParamDef(  default=0, low=0, high=127, comment='pulsewidth'),
      ),
      ParamType('Waveform',
        ParamDef(  default=0, low=0, high=3, comment='waveform1'),
      ),
      ParamType('PitchMod1',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('PitchMod2',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('FmMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('PwMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=1,
          default=1,
          high=0,
          comment='freqdisplunits'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='OscB',
    id=8,
    height=6,
    inputs=[
      InputType('FmMod',        nm1conncolors.audio),
      InputType('PitchMod1',    nm1conncolors.control),
      InputType('PitchMod2',    nm1conncolors.control),
      InputType('PwMod',        nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
      OutputType('Slv',          nm1conncolors.slave),
    ],
    params=[
      ParamType('FreqCoarse',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('FreqFine',
        ParamDef(  default=0, low=0, high=127, comment='freqfine'),
      ),
      ParamType('Kbt',
        ParamDef(  default=0, low=0, high=127, comment='freqkbt'),
      ),
      ParamType('Waveform',
        ParamDef(  default=0, low=0, high=3, comment='waveform1'),
      ),
      ParamType('PitchMod1',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('PitchMod2',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('FmMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('PwMod',
        ParamDef(  default=0, low=0, high=127, comment='pulsewidth'),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=1,
          default=1,
          high=0,
          comment='freqdisplunits'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='OscC',
    id=9,
    height=4,
    inputs=[
      InputType('FmMod',        nm1conncolors.audio),
      InputType('Pitch',        nm1conncolors.audio),
      InputType('Am',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
      OutputType('Slv',          nm1conncolors.slave),
    ],
    params=[
      ParamType('FreqCoarse',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('FreqFine',
        ParamDef(  default=0, low=0, high=127, comment='freqfine'),
      ),
      ParamType('Kbt',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('FreqMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('FmMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=1,
          default=1,
          high=0,
          comment='freqdisplunits'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='OscSlvB',
    id=10,
    height=3,
    inputs=[
      InputType('Mst',          nm1conncolors.slave),
      InputType('PwMod',        nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('DetuneCoarse',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('DetuneFine',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('PulseWidth',
        ParamDef(  default=0, low=0, high=127, comment='pulsewidth'),
      ),
      ParamType('PwMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=2,
          default=2,
          high=0,
          comment='freqdisplunits3'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='OscSlvC',
    id=11,
    height=3,
    inputs=[
      InputType('Mst',          nm1conncolors.slave),
      InputType('FmMod',        nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('DetuneCoarse',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('DetuneFine',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('FmMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=2,
          default=2,
          high=0,
          comment='freqdisplunits3'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='OscSlvD',
    id=12,
    height=3,
    inputs=[
      InputType('Mst',          nm1conncolors.slave),
      InputType('FmMod',        nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('DetuneCoarse',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('DetuneFine',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('FmMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=2,
          default=2,
          high=0,
          comment='freqdisplunits3'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='OscSlvE',
    id=13,
    height=3,
    inputs=[
      InputType('Mst',          nm1conncolors.slave),
      InputType('FmMod',        nm1conncolors.audio),
      InputType('Am',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('DetuneCoarse',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('DetuneFine',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('FmMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=2,
          default=2,
          high=0,
          comment='freqdisplunits3'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='OscSlvA',
    id=14,
    height=4,
    inputs=[
      InputType('Mst',          nm1conncolors.slave),
      InputType('FmMod',        nm1conncolors.audio),
      InputType('Am',           nm1conncolors.audio),
      InputType('Sync',         nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('DetuneCoarse',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('DetuneFine',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Waveform',
        ParamDef(  default=0, low=0, high=3, comment=''),
      ),
      ParamType('FmMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=2,
          default=2,
          high=0,
          comment='freqdisplunits3'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='NoteSeqA',
    id=15,
    height=7,
    inputs=[
      InputType('Clk',          nm1conncolors.logic),
      InputType('Reset',        nm1conncolors.logic),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
      OutputType('Snc',          nm1conncolors.logic),
      OutputType('Link',         nm1conncolors.logic),
      OutputType('Gclk',         nm1conncolors.logic),
    ],
    params=[
      ParamType('Note1',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Note2',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Note3',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Note4',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Note5',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Note6',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Note7',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Note8',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Note9',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Note10',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Note11',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Note12',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Note13',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Note14',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Note15',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Note16',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Length',
        ParamDef(  default=0, low=0, high=15, comment=''),
      ),
      ParamType('EditPosition',
        ParamDef(  default=0, low=0, high=16, comment='editpos'),
      ),
      ParamType('Record',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Pause',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Loop',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='PortamentoB',
    id=16,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.control),
      InputType('Jmp',          nm1conncolors.logic),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Time',
        ParamDef(  default=0, low=0, high=127, comment='adsrtime'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='EventSeq',
    id=17,
    height=5,
    inputs=[
      InputType('Clk',          nm1conncolors.logic),
      InputType('Rst',          nm1conncolors.logic),
    ],
    outputs=[
      OutputType('Out1',         nm1conncolors.logic),
      OutputType('Out2',         nm1conncolors.logic),
      OutputType('Snc',          nm1conncolors.logic),
      OutputType('Link',         nm1conncolors.logic),
    ],
    params=[
      ParamType('Length',
        ParamDef(  default=0, low=0, high=15, comment=''),
      ),
      ParamType('Loop',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Gate1',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Gate2',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq1Step1',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq1Step2',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq1Step3',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq1Step4',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq1Step5',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq1Step6',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq1Step7',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq1Step8',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq1Step9',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq1Step10',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq1Step11',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq1Step12',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq1Step13',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq1Step14',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq1Step15',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq1Step16',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq2Step1',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq2Step2',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq2Step3',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq2Step4',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq2Step5',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq2Step6',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq2Step7',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq2Step8',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq2Step9',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq2Step10',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq2Step11',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq2Step12',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq2Step13',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq2Step14',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq2Step15',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Seq2Step16',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='X-Fade',
    id=18,
    height=3,
    inputs=[
      InputType('In1',          nm1conncolors.audio),
      InputType('In2',          nm1conncolors.audio),
      InputType('MixMod',       nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('MixMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Mix',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='3Mixer',
    id=19,
    height=2,
    inputs=[
      InputType('In1',          nm1conncolors.audio),
      InputType('In2',          nm1conncolors.audio),
      InputType('In3',          nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Lev1',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Lev2',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Lev3',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='ADSR-Env',
    id=20,
    height=5,
    inputs=[
      InputType('In',           nm1conncolors.audio),
      InputType('Gate',         nm1conncolors.logic),
      InputType('Retrig',       nm1conncolors.logic),
      InputType('Amp',          nm1conncolors.control),
    ],
    outputs=[
      OutputType('Env',          nm1conncolors.control),
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('AttackShape',
        ParamDef(  default=0, low=0, high=2, comment='adsrshape'),
      ),
      ParamType('Attack',
        ParamDef(  default=0, low=0, high=127, comment='adsrtime'),
      ),
      ParamType('Decay',
        ParamDef(  default=0, low=0, high=127, comment='adsrtime'),
      ),
      ParamType('Sustain',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Release',
        ParamDef(  default=0, low=0, high=127, comment='adsrtime'),
      ),
      ParamType('Invert',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='Compressor',
    id=21,
    height=7,
    inputs=[
      InputType('Left',         nm1conncolors.audio),
      InputType('Right',        nm1conncolors.audio),
      InputType('Side',         nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Left',         nm1conncolors.audio),
      OutputType('Right',        nm1conncolors.audio),
    ],
    params=[
      ParamType('Attack',
        ParamDef(  default=0, low=0, high=127, comment='companderattack'),
      ),
      ParamType('Release',
        ParamDef(  default=0, low=0, high=127, comment='companderrelease'),
      ),
      ParamType('Threshold',
        ParamDef(  default=0, low=0, high=42, comment='companderthreshold'),
      ),
      ParamType('Ratio',
        ParamDef(  default=0, low=0, high=66, comment='companderratio'),
      ),
      ParamType('RefLevel',
        ParamDef(  default=0, low=0, high=42, comment='companderref'),
      ),
      ParamType('Limiter',
        ParamDef(  default=0, low=0, high=24, comment='companderlimit'),
      ),
      ParamType('Act',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Mon',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Bypass',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='PartialGen',
    id=22,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Range',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='Mod-Env',
    id=23,
    height=6,
    inputs=[
      InputType('Gate',         nm1conncolors.logic),
      InputType('Retrig',       nm1conncolors.logic),
      InputType('AttackMod',    nm1conncolors.control),
      InputType('DecayMod',     nm1conncolors.control),
      InputType('SustainMod',   nm1conncolors.control),
      InputType('ReleaseMod',   nm1conncolors.control),
      InputType('In',           nm1conncolors.audio),
      InputType('Amp',          nm1conncolors.control),
    ],
    outputs=[
      OutputType('Env',          nm1conncolors.control),
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Attack',
        ParamDef(  default=0, low=0, high=127, comment='adsrtime'),
      ),
      ParamType('Decay',
        ParamDef(  default=0, low=0, high=127, comment='adsrtime'),
      ),
      ParamType('Sustain',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Release',
        ParamDef(  default=0, low=0, high=127, comment='adsrtime'),
      ),
      ParamType('AttackMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('DecayMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('SustainMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('ReleaseMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Invert',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='LFOA',
    id=24,
    height=5,
    inputs=[
      InputType('Rate',         nm1conncolors.control),
      InputType('Reset',        nm1conncolors.logic),
    ],
    outputs=[
      OutputType('Slv',          nm1conncolors.slave),
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Rate',
        ParamDef(  default=0, low=0, high=127, comment='lforate'),
      ),
      ParamType('Range',
        ParamDef(  default=0, low=0, high=2, comment='lforange'),
      ),
      ParamType('Waveform',
        ParamDef(  default=0, low=0, high=4, comment='lfoshape'),
      ),
      ParamType('RateMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Mono',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Kbt',
        ParamDef(  default=0, low=0, high=127, comment='freqkbt'),
      ),
      ParamType('Phase',
        ParamDef(  default=0, low=0, high=127, comment='phase'),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='LFOB',
    id=25,
    height=5,
    inputs=[
      InputType('Rate',         nm1conncolors.control),
      InputType('Rst',          nm1conncolors.logic),
      InputType('Pwmod',        nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
      OutputType('Slv',          nm1conncolors.slave),
    ],
    params=[
      ParamType('Rate',
        ParamDef(  default=0, low=0, high=127, comment='lforate'),
      ),
      ParamType('Range',
        ParamDef(  default=0, low=0, high=2, comment='lforange'),
      ),
      ParamType('Phase',
        ParamDef(  default=0, low=0, high=127, comment='phase'),
      ),
      ParamType('RateMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Mono',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Kbt',
        ParamDef(  default=0, low=0, high=127, comment='freqkbt'),
      ),
      ParamType('PwMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Pw',
        ParamDef(  default=0, low=0, high=127, comment='pulsewidth'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='LFOC',
    id=26,
    height=4,
    inputs=[
      InputType('Rate',         nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
      OutputType('Slv',          nm1conncolors.slave),
    ],
    params=[
      ParamType('Rate',
        ParamDef(  default=0, low=0, high=127, comment='lforate'),
      ),
      ParamType('Range',
        ParamDef(  default=0, low=0, high=2, comment='lforange'),
      ),
      ParamType('Waveform',
        ParamDef(  default=0, low=0, high=4, comment='lfoshape'),
      ),
      ParamType('RateMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Mono',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='LFOSlvB',
    id=27,
    height=2,
    inputs=[
      InputType('Mst',          nm1conncolors.slave),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Rate',
        ParamDef(  default=0, low=0, high=127, comment='lfoslvrate'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=1,
          default=1,
          high=0,
          comment='freqdisplunitslfo'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='LFOSlvC',
    id=28,
    height=2,
    inputs=[
      InputType('Mst',          nm1conncolors.slave),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Rate',
        ParamDef(  default=0, low=0, high=127, comment='lfoslvrate'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=1,
          default=1,
          high=0,
          comment='freqdisplunitslfo'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='LFOSlvD',
    id=29,
    height=2,
    inputs=[
      InputType('Mst',          nm1conncolors.slave),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Rate',
        ParamDef(  default=0, low=0, high=127, comment='lfoslvrate'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=1,
          default=1,
          high=0,
          comment='freqdisplunitslfo'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='LFOSlvE',
    id=30,
    height=2,
    inputs=[
      InputType('Mst',          nm1conncolors.slave),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Rate',
        ParamDef(  default=0, low=0, high=127, comment='lfoslvrate'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=1,
          default=1,
          high=0,
          comment='freqdisplunitslfo'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='Noise',
    id=31,
    height=2,
    inputs=[],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Color',
        ParamDef(  default=0, low=0, high=127, comment='noisecolor'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='FilterBank',
    id=32,
    height=7,
    inputs=[
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('50',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('75',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('110',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('170',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('250',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('380',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('570',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('850',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('1.3',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('1.9',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('2.9',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('4.2',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('6.4',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('8.3',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Bypass',
        ParamDef(  default=0, low=0, high=1, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='ClkRndGen',
    id=33,
    height=2,
    inputs=[
      InputType('Clk',          nm1conncolors.logic),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Mono',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Color',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='RndStepGen',
    id=34,
    height=2,
    inputs=[
      InputType('Mst',          nm1conncolors.slave),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Rate',
        ParamDef(  default=0, low=0, high=127, comment='lfoslvrate'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='RndPulsGen',
    id=35,
    height=2,
    inputs=[],
    outputs=[
      OutputType('Out',          nm1conncolors.logic),
    ],
    params=[
      ParamType('Density',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='PosEdgeDelay',
    id=36,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.logic),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.logic),
    ],
    params=[
      ParamType('Time',
        ParamDef(  default=0, low=0, high=127, comment='logictime'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='LogicDelay',
    id=37,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.logic),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.logic),
    ],
    params=[
      ParamType('Time',
        ParamDef(  default=0, low=0, high=127, comment='logictime'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='Pulse',
    id=38,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.logic),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.logic),
    ],
    params=[
      ParamType('Time',
        ParamDef(  default=0, low=0, high=127, comment='logictime'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='Smooth',
    id=39,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Time',
        ParamDef(  default=0, low=0, high=127, comment='smoothtime'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='8Mixer',
    id=40,
    height=4,
    inputs=[
      InputType('In1',          nm1conncolors.audio),
      InputType('In2',          nm1conncolors.audio),
      InputType('In3',          nm1conncolors.audio),
      InputType('In4',          nm1conncolors.audio),
      InputType('In5',          nm1conncolors.audio),
      InputType('In6',          nm1conncolors.audio),
      InputType('In7',          nm1conncolors.audio),
      InputType('In8',          nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Lev1',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Lev2',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Lev3',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Lev4',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Lev5',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Lev6',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Lev7',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Lev8',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('-6Db',
        ParamDef(  default=0, low=0, high=1, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='Constant',
    id=43,
    height=2,
    inputs=[],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Value',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Unipolar',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='GainControl',
    id=44,
    height=2,
    inputs=[
      InputType('Control',      nm1conncolors.audio),
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Shift',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='VocalFilter',
    id=45,
    height=5,
    inputs=[
      InputType('In',           nm1conncolors.audio),
      InputType('VowelMod',     nm1conncolors.control),
      InputType('FrequencyMod', nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Vowel1',
        ParamDef(  default=0, low=0, high=8, comment='vowel'),
      ),
      ParamType('Vowel2',
        ParamDef(  default=0, low=0, high=8, comment='vowel'),
      ),
      ParamType('Vowel3',
        ParamDef(  default=0, low=0, high=8, comment='vowel'),
      ),
      ParamType('Level',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Vowel',
        ParamDef(  default=0, low=0, high=127, comment='symeteric'),
      ),
      ParamType('VowelMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Freq',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('FreqMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Res',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='AHD-Env',
    id=46,
    height=5,
    inputs=[
      InputType('Trig',         nm1conncolors.logic),
      InputType('AttackMod',    nm1conncolors.control),
      InputType('HoldMod',      nm1conncolors.control),
      InputType('DecayMod',     nm1conncolors.control),
      InputType('In',           nm1conncolors.audio),
      InputType('Amp',          nm1conncolors.control),
    ],
    outputs=[
      OutputType('Env',          nm1conncolors.control),
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Attack',
        ParamDef(  default=0, low=0, high=127, comment='adsrtime'),
      ),
      ParamType('Hold',
        ParamDef(  default=0, low=0, high=127, comment='adsrtime'),
      ),
      ParamType('Decay',
        ParamDef(  default=0, low=0, high=127, comment='adsrtime'),
      ),
      ParamType('AttackMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('HoldMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('DecayMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='Pan',
    id=47,
    height=3,
    inputs=[
      InputType('In',           nm1conncolors.audio),
      InputType('Panmod',       nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Outl',         nm1conncolors.audio),
      OutputType('Outr',         nm1conncolors.audio),
    ],
    params=[
      ParamType('PanMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Pan',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='PortamentoA',
    id=48,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.control),
      InputType('On',           nm1conncolors.logic),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Time',
        ParamDef(  default=0, low=0, high=127, comment='adsrtime'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='FilterD',
    id=49,
    height=5,
    inputs=[
      InputType('FreqMod',      nm1conncolors.control),
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Hp',           nm1conncolors.audio),
      OutputType('Bp',           nm1conncolors.audio),
      OutputType('Lp',           nm1conncolors.audio),
    ],
    params=[
      ParamType('Freq',
        ParamDef(  default=0, low=0, high=127, comment='filterfreq'),
      ),
      ParamType('Kbt',
        ParamDef(  default=0, low=0, high=127, comment='freqkbt'),
      ),
      ParamType('Res',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('FreqMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=1,
          default=1,
          high=0,
          comment='freqdisplunits'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='FilterC',
    id=50,
    height=4,
    inputs=[
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Lp',           nm1conncolors.audio),
      OutputType('Bp',           nm1conncolors.audio),
      OutputType('Hp',           nm1conncolors.audio),
    ],
    params=[
      ParamType('Freq',
        ParamDef(  default=0, low=0, high=127, comment='filterfreq'),
      ),
      ParamType('Res',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('GainControl',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=1,
          default=1,
          high=0,
          comment='freqdisplunits'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='FilterE',
    id=51,
    height=6,
    inputs=[
      InputType('FreqMod1',     nm1conncolors.audio),
      InputType('ResMod',       nm1conncolors.audio),
      InputType('In',           nm1conncolors.audio),
      InputType('FreqMod2',     nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('FilterType',
        ParamDef(  default=0, low=0, high=3, comment='filtertype'),
      ),
      ParamType('GainControl',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('FreqMod1',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Freq',
        ParamDef(  default=0, low=0, high=127, comment='filterfreq'),
      ),
      ParamType('Kbt',
        ParamDef(  default=0, low=0, high=127, comment='freqkbt'),
      ),
      ParamType('ResMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Res',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Slope',
        ParamDef(  default=0, low=0, high=1, comment='filterslope2'),
      ),
      ParamType('FreqMod2',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Bypass',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=1,
          default=1,
          high=0,
          comment='freqdisplunits'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='Multi-Env',
    id=52,
    height=7,
    inputs=[
      InputType('Gate',         nm1conncolors.logic),
      InputType('In',           nm1conncolors.audio),
      InputType('Amp',          nm1conncolors.control),
    ],
    outputs=[
      OutputType('Env',          nm1conncolors.control),
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Level1',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Level2',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Level3',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Level4',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Time1',
        ParamDef(  default=0, low=0, high=127, comment='adsrtime'),
      ),
      ParamType('Time2',
        ParamDef(  default=0, low=0, high=127, comment='adsrtime'),
      ),
      ParamType('Time3',
        ParamDef(  default=0, low=0, high=127, comment='adsrtime'),
      ),
      ParamType('Time4',
        ParamDef(  default=0, low=0, high=127, comment='adsrtime'),
      ),
      ParamType('Time5',
        ParamDef(  default=0, low=0, high=127, comment='adsrtime'),
      ),
      ParamType('Sustain',
        ParamDef(  default=0, low=0, high=4, comment='0 ~ off, 4 ~ level 4'),
      ),
      ParamType('Curve',
        ParamDef(  default=0, low=0, high=2, comment='0 ~ bipolar, 1 ~ uni/exp, 2 ~ uni/lin'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='Sample&Hold',
    id=53,
    height=2,
    inputs=[
      InputType('Trig',         nm1conncolors.logic),
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[],
    modes=[],
  ),
  ModuleType(
    shortnm='Quantizer',
    id=54,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Bits',
        ParamDef(  default=0, low=0, high=12, comment='quantbits'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='InvLevShift',
    id=57,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Mode',
        ParamDef(  default=0, low=0, high=2, comment='0 ~ bipolar, 1 ~ uni/neg, 2 ~ uni/pos'),
      ),
      ParamType('Inv',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='DrumSynth',
    id=58,
    height=9,
    inputs=[
      InputType('Trig',         nm1conncolors.logic),
      InputType('Vel',          nm1conncolors.control),
      InputType('Pitch',        nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Masterfreq',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('SlaveRatio',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('MasterDecay',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('SlaveDecay',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('MasterLevel',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('SlaveLevel',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('NoiseFltFreq',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('NoiseFltRes',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('NoiseFltSweep',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('NoiseFltDecay',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('NoiseFltMode',
        ParamDef(  default=0, low=0, high=2, comment='filtertype1'),
      ),
      ParamType('BendAmount',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('BendDecay',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Click',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Noise',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='CompareLev',
    id=59,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.logic),
    ],
    params=[
      ParamType('Level',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='Clip',
    id=61,
    height=3,
    inputs=[
      InputType('In',           nm1conncolors.audio),
      InputType('Clip',         nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('ClipMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Clip',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Sym',
        ParamDef(  default=0, low=0, high=1, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='Overdrive',
    id=62,
    height=3,
    inputs=[
      InputType('In',           nm1conncolors.audio),
      InputType('OverdriveMod', nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('OverdriveMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Overdrive',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='KeyboardPatch',
    id=63,
    height=3,
    inputs=[],
    outputs=[
      OutputType('LatestNote',   nm1conncolors.control),
      OutputType('PatchGate',    nm1conncolors.logic),
      OutputType('LatestVelOn',  nm1conncolors.control),
      OutputType('LatestRelVel', nm1conncolors.control),
    ],
    params=[],
    modes=[],
  ),
  ModuleType(
    shortnm='NegEdgeDelay',
    id=64,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.logic),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.logic),
    ],
    params=[
      ParamType('Time',
        ParamDef(  default=0, low=0, high=127, comment='logictime'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='MIDIGlobal',
    id=65,
    height=2,
    inputs=[],
    outputs=[
      OutputType('Clk',          nm1conncolors.logic),
      OutputType('Sync',         nm1conncolors.logic),
      OutputType('Active',       nm1conncolors.logic),
    ],
    params=[],
    modes=[],
  ),
  ModuleType(
    shortnm='ControlMixer',
    id=66,
    height=2,
    inputs=[
      InputType('In1',          nm1conncolors.control),
      InputType('In2',          nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Inv1',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Level1',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Inv2',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Level2',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Mode',
        ParamDef(  default=0, low=0, high=1, comment='0 ~ lin, 1 ~ exp'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='NoteDetect',
    id=67,
    height=2,
    inputs=[],
    outputs=[
      OutputType('Gate',         nm1conncolors.logic),
      OutputType('Velocity',     nm1conncolors.control),
      OutputType('Releasevelocity', nm1conncolors.control),
    ],
    params=[
      ParamType('Note',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='ClkGen',
    id=68,
    height=3,
    inputs=[
      InputType('Rst',          nm1conncolors.logic),
    ],
    outputs=[
      OutputType('24Pulses/Beat', nm1conncolors.logic),
      OutputType('4Pulses/Beat', nm1conncolors.logic),
      OutputType('Slv',          nm1conncolors.slave),
      OutputType('Sync',         nm1conncolors.logic),
    ],
    params=[
      ParamType('Rate',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('On/Off',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='ClkDiv',
    id=69,
    height=2,
    inputs=[
      InputType('Clk',          nm1conncolors.logic),
      InputType('Rst',          nm1conncolors.logic),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.logic),
    ],
    params=[
      ParamType('Divider',
        ParamDef(  default=0, low=0, high=127, comment='logicdiv'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='LogicInv',
    id=70,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.logic),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.logic),
    ],
    params=[],
    modes=[],
  ),
  ModuleType(
    shortnm='EnvFollower',
    id=71,
    height=3,
    inputs=[
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Attack',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Release',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='NoteScaler',
    id=72,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Transpose',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='LogicProc',
    id=73,
    height=2,
    inputs=[
      InputType('In1',          nm1conncolors.logic),
      InputType('In2',          nm1conncolors.logic),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.logic),
    ],
    params=[
      ParamType('Mode',
        ParamDef(  default=0, low=0, high=2, comment='0 ~ and, 1 ~ or, 2 ~ xor'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='WaveWrap',
    id=74,
    height=3,
    inputs=[
      InputType('In',           nm1conncolors.audio),
      InputType('WrapMod',      nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('WrapMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Wrap',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='NoteQuant',
    id=75,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Range',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Notes',
        ParamDef(  default=0, low=0, high=127, comment='0 ~ off'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='OnOff',
    id=76,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('On',
        ParamDef(  default=0, low=0, high=1, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='ClkDivFix',
    id=77,
    height=2,
    inputs=[
      InputType('Reset',        nm1conncolors.logic),
      InputType('MidiClock',    nm1conncolors.logic),
    ],
    outputs=[
      OutputType('16',           nm1conncolors.logic),
      OutputType('T8',           nm1conncolors.logic),
      OutputType('8',            nm1conncolors.logic),
    ],
    params=[],
    modes=[],
  ),
  ModuleType(
    shortnm='Delay',
    id=78,
    height=3,
    inputs=[
      InputType('In',           nm1conncolors.audio),
      InputType('Modulation',   nm1conncolors.control),
    ],
    outputs=[
      OutputType('FixedDelay',   nm1conncolors.audio),
      OutputType('VariableDelayOut', nm1conncolors.audio),
    ],
    params=[
      ParamType('Modulation',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Time',
        ParamDef(  default=0, low=0, high=127, comment='0 ~ 0 ms, 127 ~ 2.65 ms'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='4-1Switch',
    id=79,
    height=3,
    inputs=[
      InputType('In1',          nm1conncolors.audio),
      InputType('In2',          nm1conncolors.audio),
      InputType('In3',          nm1conncolors.audio),
      InputType('In4',          nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Sel',
        ParamDef(  default=0, low=0, high=3, comment=''),
      ),
      ParamType('Level1',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Level2',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Level3',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Level4',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='LFOSlvA',
    id=80,
    height=4,
    inputs=[
      InputType('Mst',          nm1conncolors.slave),
      InputType('Reset',        nm1conncolors.logic),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Rate',
        ParamDef(  default=0, low=0, high=127, comment='lfoslvrate'),
      ),
      ParamType('Phase',
        ParamDef(  default=0, low=0, high=127, comment='phase'),
      ),
      ParamType('Waveform',
        ParamDef(  default=0, low=0, high=4, comment='lfoshape'),
      ),
      ParamType('Mono',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=1,
          default=1,
          high=0,
          comment='freqdisplunitslfo'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='Amplifier',
    id=81,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Gain',
        ParamDef(  default=0, low=0, high=127, comment='ampgain'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='Diode',
    id=82,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Mode',
        ParamDef(  default=0, low=0, high=2, comment='0 ~ off, 1 ~ half wave, 2 ~ full wave'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='Shaper',
    id=83,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Mode',
        ParamDef(  default=0, low=0, high=4, comment='0 ~ log2, 1 ~ log1, 2 ~ lin, 3 ~ exp1, 4 ~ exp2'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='AD-Env',
    id=84,
    height=3,
    inputs=[
      InputType('Trigger',      nm1conncolors.logic),
      InputType('In',           nm1conncolors.audio),
      InputType('Amp',          nm1conncolors.control),
    ],
    outputs=[
      OutputType('Envelope',     nm1conncolors.control),
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Attack',
        ParamDef(  default=0, low=0, high=127, comment='adsrtime'),
      ),
      ParamType('Decay',
        ParamDef(  default=0, low=0, high=127, comment='adsrtime'),
      ),
      ParamType('Gate',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='OscSlvFM',
    id=85,
    height=3,
    inputs=[
      InputType('Mst',          nm1conncolors.slave),
      InputType('FmMod',        nm1conncolors.audio),
      InputType('Sync',         nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('DetuneCoarse',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('DetuneFine',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('-3Oct',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('FmMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=1,
          default=1,
          high=0,
          comment='freqdisplunits'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='FilterA',
    id=86,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Freq',
        ParamDef(  default=0, low=0, high=127, comment='filterfreqAB'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='FilterB',
    id=87,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Freq',
        ParamDef(  default=0, low=0, high=127, comment='filterfreqAB'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='1-4Switch',
    id=88,
    height=3,
    inputs=[
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out1',         nm1conncolors.audio),
      OutputType('Out2',         nm1conncolors.audio),
      OutputType('Out3',         nm1conncolors.audio),
      OutputType('Out4',         nm1conncolors.audio),
    ],
    params=[
      ParamType('Sel',
        ParamDef(  default=0, low=0, high=3, comment='0 ~ out1, 3 ~ out4'),
      ),
      ParamType('Level',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='CompareAB',
    id=89,
    height=2,
    inputs=[
      InputType('A',            nm1conncolors.control),
      InputType('B',            nm1conncolors.control),
    ],
    outputs=[
      OutputType('A>=B',         nm1conncolors.logic),
    ],
    params=[],
    modes=[],
  ),
  ModuleType(
    shortnm='NoteSeqB',
    id=90,
    height=9,
    inputs=[
      InputType('Clk',          nm1conncolors.logic),
      InputType('Rst',          nm1conncolors.logic),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
      OutputType('Snc',          nm1conncolors.logic),
      OutputType('Link',         nm1conncolors.logic),
      OutputType('Gclk',         nm1conncolors.logic),
    ],
    params=[
      ParamType('Note1',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('Note2',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('Note3',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('Note4',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('Note5',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('Note6',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('Note7',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('Note8',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('Note9',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('Note10',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('Note11',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('Note12',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('Note13',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('Note14',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('Note15',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('Note16',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('Length',
        ParamDef(  default=0, low=0, high=15, comment=''),
      ),
      ParamType('Currentstep',
        ParamDef(  default=0, low=0, high=16, comment='editpos'),
      ),
      ParamType('Record',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Play',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Loop',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[
      ModeType('Zoomfactor',
        ParamDef(  
          low=6,
          default=6,
          high=1,
          comment=''
        ),
      ),
      ModeType('Sliderposition',
        ParamDef(  
          low=117,
          default=117,
          high=6,
          comment=''
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='CtrlSeq',
    id=91,
    height=7,
    inputs=[
      InputType('Clk',          nm1conncolors.logic),
      InputType('Rst',          nm1conncolors.logic),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
      OutputType('Snc',          nm1conncolors.logic),
      OutputType('Link',         nm1conncolors.logic),
    ],
    params=[
      ParamType('Ctrl1',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Ctrl2',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Ctrl3',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Ctrl4',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Ctrl5',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Ctrl6',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Ctrl7',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Ctrl8',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Ctrl9',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Ctrl10',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Ctrl11',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Ctrl12',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Ctrl13',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Ctrl14',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Ctrl15',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Ctrl16',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Length',
        ParamDef(  default=0, low=0, high=15, comment=''),
      ),
      ParamType('Uni',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Loop',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='FilterF',
    id=92,
    height=6,
    inputs=[
      InputType('FreqMod1',     nm1conncolors.control),
      InputType('FreqMod2',     nm1conncolors.control),
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Freq',
        ParamDef(  default=0, low=0, high=127, comment='filterfreq'),
      ),
      ParamType('Kbt',
        ParamDef(  default=0, low=0, high=127, comment='freqkbt'),
      ),
      ParamType('Res',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('FreqMod1',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('FreqMod2',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Slope',
        ParamDef(  default=0, low=0, high=2, comment='filtertype1'),
      ),
      ParamType('Bypass',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=1,
          default=1,
          high=0,
          comment='freqdisplunits'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='StereoChorus',
    id=94,
    height=3,
    inputs=[
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Outleft',      nm1conncolors.audio),
      OutputType('Outright',     nm1conncolors.audio),
    ],
    params=[
      ParamType('Detune',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Amount',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Bypass',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='PercOsc',
    id=95,
    height=4,
    inputs=[
      InputType('Trig',         nm1conncolors.audio),
      InputType('Am',           nm1conncolors.audio),
      InputType('PitchMod',     nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('FreqCoarse',
        ParamDef(  default=0, low=0, high=127, comment='0 ~ 8.18 Hz, 127 ~ 12.54 kHz'),
      ),
      ParamType('Click',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Decay',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Punch',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('PitchMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('FreqFine',
        ParamDef(  default=0, low=0, high=127, comment='freqfine'),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=1,
          default=1,
          high=0,
          comment='freqdisplunits'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='FormantOsc',
    id=96,
    height=4,
    inputs=[
      InputType('PitchMod1',    nm1conncolors.control),
      InputType('PitchMod2',    nm1conncolors.control),
      InputType('Timbre',       nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
      OutputType('Slv',          nm1conncolors.slave),
    ],
    params=[
      ParamType('FreqCoarse',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('FreqFine',
        ParamDef(  default=0, low=0, high=127, comment='freqfine'),
      ),
      ParamType('Kbt',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Timbre',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('PitchMod1',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('PitchMod2',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=1,
          default=1,
          high=0,
          comment='freqdisplunits'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='MasterOsc',
    id=97,
    height=3,
    inputs=[
      InputType('PitchMod1',    nm1conncolors.control),
      InputType('PitchMod2',    nm1conncolors.control),
    ],
    outputs=[
      OutputType('Slv',          nm1conncolors.slave),
    ],
    params=[
      ParamType('FreqCoarse',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('FreqFine',
        ParamDef(  default=0, low=0, high=127, comment='freqfine'),
      ),
      ParamType('Kbt',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('PitchMod1',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('PitchMod2',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=1,
          default=1,
          high=0,
          comment='freqdisplunits'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='KeyQuant',
    id=98,
    height=4,
    inputs=[
      InputType('In',           nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Range',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Cont',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('E',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('F',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('F#',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('G',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('G#',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('A',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('A#',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('B',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('C',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('C#',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('D',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('D#',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='PatternGen',
    id=99,
    height=4,
    inputs=[
      InputType('Clk',          nm1conncolors.logic),
      InputType('Rst',          nm1conncolors.logic),
      InputType('Pattern&Bank', nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Pattern',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Bank',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('LowDelta',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Step',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Mono',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='KeyboardSplit',
    id=100,
    height=3,
    inputs=[
      InputType('Note',         nm1conncolors.control),
      InputType('Gate',         nm1conncolors.logic),
      InputType('Vel',          nm1conncolors.control),
    ],
    outputs=[
      OutputType('Note',         nm1conncolors.control),
      OutputType('Gate',         nm1conncolors.logic),
      OutputType('Vel',          nm1conncolors.control),
    ],
    params=[
      ParamType('Upper',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('Lower',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='Phaser',
    id=102,
    height=7,
    inputs=[
      InputType('In',           nm1conncolors.audio),
      InputType('FreqMod',      nm1conncolors.control),
      InputType('SpreadMod',    nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Rate',
        ParamDef(  default=0, low=0, high=127, comment='0 ~ 62.9 s, 127 ~ 24.4 hHz'),
      ),
      ParamType('Lfo',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('FreqMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Freq',
        ParamDef(  default=0, low=0, high=127, comment='0 ~ 100 Hz, 127 ~ 16 kHz'),
      ),
      ParamType('SpreadMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Feedback',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Peaks',
        ParamDef(  default=0, low=0, high=5, comment='0 ~ 1 peak, 5 ~ 6 peaks'),
      ),
      ParamType('Spread',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Bypass',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Depth',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Level',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='EqMid',
    id=103,
    height=4,
    inputs=[
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Freq',
        ParamDef(  default=0, low=0, high=127, comment='eqfreq'),
      ),
      ParamType('Gain',
        ParamDef(  default=0, low=0, high=127, comment='eqgain'),
      ),
      ParamType('Bandwidth',
        ParamDef(  default=0, low=0, high=127, comment='0 ~ 2 oct, 64 ~ 1 oct, 127 ~ 0.02 oct'),
      ),
      ParamType('Bypass',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Level',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='EqShelving',
    id=104,
    height=4,
    inputs=[
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Freq',
        ParamDef(  default=0, low=0, high=127, comment='eqfreq'),
      ),
      ParamType('Gain',
        ParamDef(  default=0, low=0, high=127, comment='eqgain'),
      ),
      ParamType('Mode',
        ParamDef(  default=0, low=0, high=1, comment='0 ~ low, 1 ~ high'),
      ),
      ParamType('Bypass',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Level',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='Expander',
    id=105,
    height=7,
    inputs=[
      InputType('InLeft',       nm1conncolors.audio),
      InputType('InRight',      nm1conncolors.audio),
      InputType('Sidechain',    nm1conncolors.audio),
    ],
    outputs=[
      OutputType('OutLeft',      nm1conncolors.audio),
      OutputType('OutRight',     nm1conncolors.audio),
    ],
    params=[
      ParamType('Attack',
        ParamDef(  default=0, low=0, high=127, comment='companderattack'),
      ),
      ParamType('Release',
        ParamDef(  default=0, low=0, high=127, comment='companderrelease'),
      ),
      ParamType('Threshold',
        ParamDef(  default=0, low=0, high=84, comment='companderthreshold'),
      ),
      ParamType('Ratio',
        ParamDef(  default=0, low=0, high=66, comment='companderratio'),
      ),
      ParamType('Gate',
        ParamDef(  default=0, low=0, high=72, comment='compandergate'),
      ),
      ParamType('Hold',
        ParamDef(  default=0, low=0, high=127, comment='companderhold'),
      ),
      ParamType('Act',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Mon',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Bypass',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='OscSineBank',
    id=106,
    height=10,
    inputs=[
      InputType('Mst',          nm1conncolors.slave),
      InputType('Mixin',        nm1conncolors.audio),
      InputType('Sync',         nm1conncolors.audio),
      InputType('Osc1Am',       nm1conncolors.audio),
      InputType('Osc2Am',       nm1conncolors.audio),
      InputType('Osc3Am',       nm1conncolors.audio),
      InputType('Osc4Am',       nm1conncolors.audio),
      InputType('Osc5Am',       nm1conncolors.audio),
      InputType('Osc6Am',       nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Osc1Coarse',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Osc1Fine',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Osc1Level',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Osc2Coarse',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Osc2Fine',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Osc2Level',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Osc3Coarse',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Osc3Fine',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Osc3Level',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Osc4Coarse',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Osc4Fine',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Osc4Level',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Osc5Coarse',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Osc5Fine',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Osc5Level',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Osc6Coarse',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Osc6Fine',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
      ParamType('Osc6Level',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Osc1Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Osc2Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Osc3Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Osc4Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Osc5Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Osc6Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='SpectralOsc',
    id=107,
    height=5,
    inputs=[
      InputType('FmMod',        nm1conncolors.audio),
      InputType('PitchMod1',    nm1conncolors.control),
      InputType('PitchMod2',    nm1conncolors.control),
      InputType('ShapeMod',     nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
      OutputType('Slv',          nm1conncolors.slave),
    ],
    params=[
      ParamType('FreqCoarse',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('FreqFine',
        ParamDef(  default=0, low=0, high=127, comment='freqfine'),
      ),
      ParamType('Shape',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Partials',
        ParamDef(  default=0, low=0, high=1, comment='0 ~ odd, 1 ~ all'),
      ),
      ParamType('PitchMod1',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('PitchMod2',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('FmMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('ShapeMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Kbt',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('Mute',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[
      ModeType('FreqDisplayUnits',
        ParamDef(  
          low=1,
          default=1,
          high=0,
          comment='freqdisplunits'
        ),
      ),
    ],
  ),
  ModuleType(
    shortnm='Vocoder',
    id=108,
    height=8,
    inputs=[
      InputType('Control',      nm1conncolors.audio),
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Band1',
        ParamDef(  default=0, low=0, high=16, comment='vocoband'),
      ),
      ParamType('Band2',
        ParamDef(  default=0, low=0, high=16, comment='vocoband'),
      ),
      ParamType('Band3',
        ParamDef(  default=0, low=0, high=16, comment='vocoband'),
      ),
      ParamType('Band4',
        ParamDef(  default=0, low=0, high=16, comment='vocoband'),
      ),
      ParamType('Band5',
        ParamDef(  default=0, low=0, high=16, comment='vocoband'),
      ),
      ParamType('Band6',
        ParamDef(  default=0, low=0, high=16, comment='vocoband'),
      ),
      ParamType('Band7',
        ParamDef(  default=0, low=0, high=16, comment='vocoband'),
      ),
      ParamType('Band8',
        ParamDef(  default=0, low=0, high=16, comment='vocoband'),
      ),
      ParamType('Band9',
        ParamDef(  default=0, low=0, high=16, comment='vocoband'),
      ),
      ParamType('Band10',
        ParamDef(  default=0, low=0, high=16, comment='vocoband'),
      ),
      ParamType('Band11',
        ParamDef(  default=0, low=0, high=16, comment='vocoband'),
      ),
      ParamType('Band12',
        ParamDef(  default=0, low=0, high=16, comment='vocoband'),
      ),
      ParamType('Band13',
        ParamDef(  default=0, low=0, high=16, comment='vocoband'),
      ),
      ParamType('Band14',
        ParamDef(  default=0, low=0, high=16, comment='vocoband'),
      ),
      ParamType('Band15',
        ParamDef(  default=0, low=0, high=16, comment='vocoband'),
      ),
      ParamType('Band16',
        ParamDef(  default=0, low=0, high=16, comment='vocoband'),
      ),
      ParamType('Outgain',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('Emphasis',
        ParamDef(  default=0, low=0, high=1, comment=''),
      ),
      ParamType('Monitor',
        ParamDef(  default=0, low=0, high=1, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='RandomGen',
    id=110,
    height=2,
    inputs=[
      InputType('Mst',          nm1conncolors.slave),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('Rate',
        ParamDef(  default=0, low=0, high=127, comment='lfoslvrate'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='LevMult',
    id=111,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Gain',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Unipolar',
        ParamDef(  default=0, low=0, high=1, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='LevAdd',
    id=112,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Level',
        ParamDef(  default=0, low=0, high=127, comment='unibi'),
      ),
      ParamType('Unipolar',
        ParamDef(  default=0, low=0, high=1, comment=''),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='1to2Fade',
    id=113,
    height=2,
    inputs=[
      InputType('In',           nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out1',         nm1conncolors.audio),
      OutputType('Out2',         nm1conncolors.audio),
    ],
    params=[
      ParamType('Mix',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='2to1Fade',
    id=114,
    height=2,
    inputs=[
      InputType('In1',          nm1conncolors.audio),
      InputType('In2',          nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Mix',
        ParamDef(  default=0, low=0, high=127, comment='symetric'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='NoteVelScal',
    id=115,
    height=4,
    inputs=[
      InputType('Velocity',     nm1conncolors.control),
      InputType('Note',         nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.control),
    ],
    params=[
      ParamType('VelocitySensitivity',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('LeftGain',
        ParamDef(  default=0, low=0, high=48, comment='velscalgain'),
      ),
      ParamType('Breakpoint',
        ParamDef(  default=0, low=0, high=127, comment='freqcoarse'),
      ),
      ParamType('RightGain',
        ParamDef(  default=0, low=0, high=48, comment='velscalgain'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='RingMod',
    id=117,
    height=3,
    inputs=[
      InputType('In',           nm1conncolors.audio),
      InputType('Mod',          nm1conncolors.audio),
      InputType('ModDepth',     nm1conncolors.audio),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('ModDepth',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('RingmodDepth',
        ParamDef(  default=0, low=0, high=127, comment='0 ~ 0, 64 ~ AM, 127 ~ RM'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='Digitizer',
    id=118,
    height=3,
    inputs=[
      InputType('In',           nm1conncolors.audio),
      InputType('RateMod',      nm1conncolors.control),
    ],
    outputs=[
      OutputType('Out',          nm1conncolors.audio),
    ],
    params=[
      ParamType('Bits',
        ParamDef(  default=0, low=0, high=11, comment='quantbits'),
      ),
      ParamType('Rate',
        ParamDef(  default=0, low=0, high=127, comment='0 ~ 34.65 Hz, 127 ~ 50.18 kHz'),
      ),
      ParamType('RateMod',
        ParamDef(  default=0, low=0, high=127, comment=''),
      ),
      ParamType('QuantOff',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
      ParamType('SamplingOff',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
  ModuleType(
    shortnm='PolyAreaIn',
    id=127,
    height=2,
    inputs=[],
    outputs=[
      OutputType('Left',         nm1conncolors.audio),
      OutputType('Right',        nm1conncolors.audio),
    ],
    params=[
      ParamType('+6Db',
        ParamDef(  default=0, low=0, high=1, comment='onoff'),
      ),
    ],
    modes=[],
  ),
]

__fromid = {}
__fromname = {}
modulemap = ModuleMap()
for module in modules:
  __fromname[module.shortnm.lower()] = module
  __fromid[module.id] = module
  name = module.shortnm.replace('-', '_').replace('&', 'n')
  setattr(modulemap, name, module)

def fromname(name): return __fromname[name.lower()]
def fromid(id): return __fromid[id]

if __name__ == '__main__':
  for module in modules:
    printf('%s.id: %d(0x%02x)\n', module.shortnm, module.id, module.id)
    for i in range(len(module.inputs)):
      input = module.inputs[i]
      printf(' .inputs[%d] .%s\n', i, input.name)
    for i in range(len(module.outputs)):
      output = module.outputs[i]
      printf(' .outputs[%d] .%s\n', i, output.name)
    for i in range(len(module.params)):
      param = module.params[i]
      printf(' .params[%d] .%s\n', i, param.name)
    for i in range(len(module.modes)):
      mode = module.modes[i]
      printf(' .modes[%d] .%s\n', i, mode.name)
