#!/usr/bin/env python

class Struct:
  def __init__(self, **kw):
    self.__dict__ = kw

class Module(Struct): pass
class Input(Struct): pass
class Output(Struct): pass
class Parameter(Struct): pass
class Custom(Struct): pass

class ModuleMap(Struct): pass

modules = [
  Module(
    name='Keyboard',
    type=1,
    height=2,
    inputs=[],
    outputs=[
      Output(name='Note',         type='Control'),
      Output(name='Gate',         type='Logic'),
      Output(name='VelocityOn',   type='Control'),
      Output(name='VelocityOff',  type='Control'),
    ],
    parameters=[],
    customs=[],
  ),
  Module(
    name='AudioIn',
    type=2,
    height=2,
    inputs=[],
    outputs=[
      Output(name='Left',         type='Audio'),
      Output(name='Right',        type='Audio'),
    ],
    parameters=[],
    customs=[],
  ),
  Module(
    name='4Output',
    type=3,
    height=3,
    inputs=[
      Input(name='Out1',         type='Audio'),
      Input(name='Out2',         type='Audio'),
      Input(name='Out3',         type='Audio'),
      Input(name='Out4',         type='Audio'),
    ],
    outputs=[],
    parameters=[
      Parameter(
        name='Level',
        low=0,
        high=127,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='2Output',
    type=4,
    height=3,
    inputs=[
      Input(name='OutLeft',      type='Audio'),
      Input(name='OutRight',     type='Audio'),
    ],
    outputs=[],
    parameters=[
      Parameter(
        name='Level',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Destination',
        low=0,
        high=2,
        comment='2destination'
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='1Output',
    type=5,
    height=3,
    inputs=[
      Input(name='Out',          type='Audio'),
    ],
    outputs=[],
    parameters=[
      Parameter(
        name='Level',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Dest',
        low=0,
        high=5,
        comment='1destination'
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='OscA',
    type=7,
    height=6,
    inputs=[
      Input(name='Sync',         type='Audio'),
      Input(name='Fma',          type='Audio'),
      Input(name='Pitch1',       type='Audio'),
      Input(name='Pitch2',       type='Audio'),
      Input(name='PulseWidthMod',type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
      Output(name='Slv',          type='Slave'),
    ],
    parameters=[
      Parameter(
        name='FreqCoarse',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='FreqFine',
        low=0,
        high=127,
        comment='freqfine'
      ),
      Parameter(
        name='FreqKbt',
        low=0,
        high=127,
        comment='freqkbt'
      ),
      Parameter(
        name='PulseWidth',
        low=0,
        high=127,
        comment='pulsewidth'
      ),
      Parameter(
        name='Waveform',
        low=0,
        high=3,
        comment='waveform1'
      ),
      Parameter(
        name='PitchMod1',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='PitchMod2',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='FmaMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='PwMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=1,
        high=0,
        comment='freqdisplunits'
      ),
    ],
  ),
  Module(
    name='OscB',
    type=8,
    height=6,
    inputs=[
      Input(name='Fma',          type='Audio'),
      Input(name='Pitch1',       type='Control'),
      Input(name='Pitch2',       type='Control'),
      Input(name='PwMod',        type='Control'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
      Output(name='Slv',          type='Slave'),
    ],
    parameters=[
      Parameter(
        name='FreqCoarse',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='FreqFine',
        low=0,
        high=127,
        comment='freqfine'
      ),
      Parameter(
        name='FreqKbt',
        low=0,
        high=127,
        comment='freqkbt'
      ),
      Parameter(
        name='Waveform',
        low=0,
        high=3,
        comment='waveform1'
      ),
      Parameter(
        name='PitchMod1',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='PitchMod2',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='FmaMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Pwidth',
        low=0,
        high=127,
        comment='pulsewidth'
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=1,
        high=0,
        comment='freqdisplunits'
      ),
    ],
  ),
  Module(
    name='OscC',
    type=9,
    height=4,
    inputs=[
      Input(name='Fma',          type='Audio'),
      Input(name='Pitch',        type='Audio'),
      Input(name='Am',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
      Output(name='Slv',          type='Slave'),
    ],
    parameters=[
      Parameter(
        name='PitchCoarse',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='PitchFine',
        low=0,
        high=127,
        comment='freqfine'
      ),
      Parameter(
        name='PitchKbt',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='PitchModAmount',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Fma',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=1,
        high=0,
        comment='freqdisplunits'
      ),
    ],
  ),
  Module(
    name='OscSlvB',
    type=10,
    height=3,
    inputs=[
      Input(name='Mst',          type='Slave'),
      Input(name='Pwmod',        type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='DetuneCoarse',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='DetuneFine',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Pw',
        low=0,
        high=127,
        comment='pulsewidth'
      ),
      Parameter(
        name='PwMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=2,
        high=0,
        comment='freqdisplunits3'
      ),
    ],
  ),
  Module(
    name='OscSlvC',
    type=11,
    height=3,
    inputs=[
      Input(name='Mst',          type='Slave'),
      Input(name='Fma',          type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='DetuneCoarse',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='DetuneFine',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='FmaMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=2,
        high=0,
        comment='freqdisplunits3'
      ),
    ],
  ),
  Module(
    name='OscSlvD',
    type=12,
    height=3,
    inputs=[
      Input(name='Mst',          type='Slave'),
      Input(name='Fma',          type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='DetuneCoarse',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='DetuneFine',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='FmaMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=2,
        high=0,
        comment='freqdisplunits3'
      ),
    ],
  ),
  Module(
    name='OscSlvE',
    type=13,
    height=3,
    inputs=[
      Input(name='Mst',          type='Slave'),
      Input(name='Fma',          type='Audio'),
      Input(name='Am',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='DetuneCoarse',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='DetuneFine',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='FmaMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=2,
        high=0,
        comment='freqdisplunits3'
      ),
    ],
  ),
  Module(
    name='OscSlvA',
    type=14,
    height=4,
    inputs=[
      Input(name='Mst',          type='Slave'),
      Input(name='Fma',          type='Audio'),
      Input(name='Am',           type='Audio'),
      Input(name='Sync',         type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='DetuneCoarse',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='DetuneFine',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Shape',
        low=0,
        high=3,
        comment=''
      ),
      Parameter(
        name='FmaMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=2,
        high=0,
        comment='freqdisplunits3'
      ),
    ],
  ),
  Module(
    name='NoteSeqA',
    type=15,
    height=7,
    inputs=[
      Input(name='Sync',         type='Logic'),
      Input(name='Reset',        type='Logic'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
      Output(name='Sync',         type='Logic'),
      Output(name='Link',         type='Logic'),
      Output(name='Gclk',         type='Logic'),
    ],
    parameters=[
      Parameter(
        name='Step1',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Step2',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Step3',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Step4',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Step5',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Step6',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Step7',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Step8',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Step9',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Step10',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Step11',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Step12',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Step13',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Step14',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Step15',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Step16',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='StepCount',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='EditPosition',
        low=0,
        high=16,
        comment='editpos'
      ),
      Parameter(
        name='Record',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Pause',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Active',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='PortamentoB',
    type=16,
    height=2,
    inputs=[
      Input(name='In',           type='Control'),
      Input(name='Jmp',          type='Logic'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Time',
        low=0,
        high=127,
        comment='adsrtime'
      ),
    ],
    customs=[],
  ),
  Module(
    name='EventSeq',
    type=17,
    height=5,
    inputs=[
      Input(name='Clock',        type='Logic'),
      Input(name='Reset',        type='Logic'),
    ],
    outputs=[
      Output(name='Out1',         type='Logic'),
      Output(name='Out2',         type='Logic'),
      Output(name='Sync',         type='Logic'),
      Output(name='Link',         type='Logic'),
    ],
    parameters=[
      Parameter(
        name='Stepcount',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Active',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Gate1',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Gate2',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq1,Step1',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq1,Step2',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq1,Step3',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq1,Step4',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq1,Step5',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq1,Step6',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq1,Step7',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq1,Step8',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq1,Step9',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq1,Step10',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq1,Step11',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq1,Step12',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq1,Step13',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq1,Step14',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq1,Step15',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq1,Step16',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq2,Step1',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq2,Step2',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq2,Step3',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq2,Step4',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq2,Step5',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq2,Step6',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq2,Step7',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq2,Step8',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq2,Step9',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq2,Step10',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq2,Step11',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq2,Step12',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq2,Step13',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq2,Step14',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq2,Step15',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Seq2,Step16',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='X-Fade',
    type=18,
    height=3,
    inputs=[
      Input(name='In1',          type='Audio'),
      Input(name='In2',          type='Audio'),
      Input(name='Modulation',   type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Modulation',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Crossfade',
        low=0,
        high=127,
        comment='symetric'
      ),
    ],
    customs=[],
  ),
  Module(
    name='Mixer',
    type=19,
    height=2,
    inputs=[
      Input(name='In1',          type='Audio'),
      Input(name='In2',          type='Audio'),
      Input(name='In3',          type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='InSense1',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='InSense2',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='InSense3',
        low=0,
        high=127,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='ADSR-Env',
    type=20,
    height=5,
    inputs=[
      Input(name='In',           type='Audio'),
      Input(name='Gate',         type='Logic'),
      Input(name='Retrig',       type='Logic'),
      Input(name='Amp',          type='Control'),
    ],
    outputs=[
      Output(name='Env',          type='Control'),
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='AttackShape',
        low=0,
        high=2,
        comment='adsrshape'
      ),
      Parameter(
        name='Attack',
        low=0,
        high=127,
        comment='adsrtime'
      ),
      Parameter(
        name='Decay',
        low=0,
        high=127,
        comment='adsrtime'
      ),
      Parameter(
        name='Sustain',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Release',
        low=0,
        high=127,
        comment='adsrtime'
      ),
      Parameter(
        name='Invert',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='Compressor',
    type=21,
    height=7,
    inputs=[
      Input(name='Left',         type='Audio'),
      Input(name='Right',        type='Audio'),
      Input(name='Side',         type='Audio'),
    ],
    outputs=[
      Output(name='Left',         type='Audio'),
      Output(name='Right',        type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Attack',
        low=0,
        high=127,
        comment='companderattack'
      ),
      Parameter(
        name='Release',
        low=0,
        high=127,
        comment='companderrelease'
      ),
      Parameter(
        name='Treshold',
        low=0,
        high=42,
        comment='compandertreshold'
      ),
      Parameter(
        name='Ratio',
        low=0,
        high=66,
        comment='companderratio'
      ),
      Parameter(
        name='RefLevel',
        low=0,
        high=42,
        comment='companderref'
      ),
      Parameter(
        name='Limiter',
        low=0,
        high=24,
        comment='companderlimit'
      ),
      Parameter(
        name='Act',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Mon',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Bypass',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='PartialGen',
    type=22,
    height=2,
    inputs=[
      Input(name='In',           type='Control'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Range',
        low=0,
        high=127,
        comment='symetric'
      ),
    ],
    customs=[],
  ),
  Module(
    name='Mod-Env',
    type=23,
    height=6,
    inputs=[
      Input(name='Gate',         type='Logic'),
      Input(name='Retrig',       type='Logic'),
      Input(name='AttackMod',    type='Control'),
      Input(name='DecayMod',     type='Control'),
      Input(name='SustainMod',   type='Control'),
      Input(name='ReleaseMod',   type='Control'),
      Input(name='In',           type='Audio'),
      Input(name='Amp',          type='Control'),
    ],
    outputs=[
      Output(name='Env',          type='Control'),
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Attack',
        low=0,
        high=127,
        comment='adsrtime'
      ),
      Parameter(
        name='Decay',
        low=0,
        high=127,
        comment='adsrtime'
      ),
      Parameter(
        name='Sustain',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Release',
        low=0,
        high=127,
        comment='adsrtime'
      ),
      Parameter(
        name='AttackMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='DecayMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='SustainMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='ReleaseMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Invert',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='LFOA',
    type=24,
    height=5,
    inputs=[
      Input(name='Rate',         type='Control'),
      Input(name='Reset',        type='Logic'),
    ],
    outputs=[
      Output(name='Slv',          type='Slave'),
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Rate',
        low=0,
        high=127,
        comment='lforate'
      ),
      Parameter(
        name='Range',
        low=0,
        high=2,
        comment='lforange'
      ),
      Parameter(
        name='Waveform',
        low=0,
        high=4,
        comment='lfoshape'
      ),
      Parameter(
        name='RateMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Mono',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='RateKbt',
        low=0,
        high=127,
        comment='freqkbt'
      ),
      Parameter(
        name='Phase',
        low=0,
        high=127,
        comment='phase'
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='LFOB',
    type=25,
    height=5,
    inputs=[
      Input(name='Rate',         type='Control'),
      Input(name='Rst',          type='Logic'),
      Input(name='Pwmod',        type='Control'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
      Output(name='Slv',          type='Slave'),
    ],
    parameters=[
      Parameter(
        name='Rate',
        low=0,
        high=127,
        comment='lforate'
      ),
      Parameter(
        name='Range',
        low=0,
        high=2,
        comment='lforange'
      ),
      Parameter(
        name='Phase',
        low=0,
        high=127,
        comment='phase'
      ),
      Parameter(
        name='RateMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Mono',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='RateKbt',
        low=0,
        high=127,
        comment='freqkbt'
      ),
      Parameter(
        name='PwMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Pw',
        low=0,
        high=127,
        comment='pulsewidth'
      ),
    ],
    customs=[],
  ),
  Module(
    name='LFOC',
    type=26,
    height=4,
    inputs=[
      Input(name='Rate',         type='Control'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
      Output(name='Slv',          type='Slave'),
    ],
    parameters=[
      Parameter(
        name='Rate',
        low=0,
        high=127,
        comment='lforate'
      ),
      Parameter(
        name='Range',
        low=0,
        high=2,
        comment='lforange'
      ),
      Parameter(
        name='Waveform',
        low=0,
        high=4,
        comment='lfoshape'
      ),
      Parameter(
        name='RateMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Mono',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='LFOSlvB',
    type=27,
    height=2,
    inputs=[
      Input(name='Mst',          type='Slave'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Rate',
        low=0,
        high=127,
        comment='lfoslvrate'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=1,
        high=0,
        comment='freqdisplunitslfo'
      ),
    ],
  ),
  Module(
    name='LFOSlvC',
    type=28,
    height=2,
    inputs=[
      Input(name='Mst',          type='Slave'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Rate',
        low=0,
        high=127,
        comment='lfoslvrate'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=1,
        high=0,
        comment='freqdisplunitslfo'
      ),
    ],
  ),
  Module(
    name='LFOSlvD',
    type=29,
    height=2,
    inputs=[
      Input(name='Mst',          type='Slave'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Rate',
        low=0,
        high=127,
        comment='lfoslvrate'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=1,
        high=0,
        comment='freqdisplunitslfo'
      ),
    ],
  ),
  Module(
    name='LFOSlvE',
    type=30,
    height=2,
    inputs=[
      Input(name='Mst',          type='Slave'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Rate',
        low=0,
        high=127,
        comment='lfoslvrate'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=1,
        high=0,
        comment='freqdisplunitslfo'
      ),
    ],
  ),
  Module(
    name='Noise',
    type=31,
    height=2,
    inputs=[],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Color',
        low=0,
        high=127,
        comment='noisecolor'
      ),
    ],
    customs=[],
  ),
  Module(
    name='FilterBank',
    type=32,
    height=7,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='50',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='75',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='110',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='170',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='250',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='380',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='570',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='850',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='1.3',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='1.9',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='2.9',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='4.2',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='6.4',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='8.3',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Bypass',
        low=0,
        high=1,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='ClkRndGen',
    type=33,
    height=2,
    inputs=[
      Input(name='Clk',          type='Logic'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Mono',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Col',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='RndStepGen',
    type=34,
    height=2,
    inputs=[
      Input(name='Mst',          type='Slave'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Rate',
        low=0,
        high=127,
        comment='lfoslvrate'
      ),
    ],
    customs=[],
  ),
  Module(
    name='RndPulsGen',
    type=35,
    height=2,
    inputs=[],
    outputs=[
      Output(name='Out',          type='Logic'),
    ],
    parameters=[
      Parameter(
        name='Density',
        low=0,
        high=127,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='PosEdgeDelay',
    type=36,
    height=2,
    inputs=[
      Input(name='In',           type='Logic'),
    ],
    outputs=[
      Output(name='Out',          type='Logic'),
    ],
    parameters=[
      Parameter(
        name='Time',
        low=0,
        high=127,
        comment='logictime'
      ),
    ],
    customs=[],
  ),
  Module(
    name='LogicDelay',
    type=37,
    height=2,
    inputs=[
      Input(name='In',           type='Logic'),
    ],
    outputs=[
      Output(name='Out',          type='Logic'),
    ],
    parameters=[
      Parameter(
        name='Time',
        low=0,
        high=127,
        comment='logictime'
      ),
    ],
    customs=[],
  ),
  Module(
    name='Pulse',
    type=38,
    height=2,
    inputs=[
      Input(name='In',           type='Logic'),
    ],
    outputs=[
      Output(name='Out',          type='Logic'),
    ],
    parameters=[
      Parameter(
        name='Time',
        low=0,
        high=127,
        comment='logictime'
      ),
    ],
    customs=[],
  ),
  Module(
    name='Smooth',
    type=39,
    height=2,
    inputs=[
      Input(name='In',           type='Control'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Time',
        low=0,
        high=127,
        comment='smoothtime'
      ),
    ],
    customs=[],
  ),
  Module(
    name='Mixer',
    type=40,
    height=4,
    inputs=[
      Input(name='In1',          type='Audio'),
      Input(name='In2',          type='Audio'),
      Input(name='In3',          type='Audio'),
      Input(name='In3',          type='Audio'),
      Input(name='In4',          type='Audio'),
      Input(name='In5',          type='Audio'),
      Input(name='In6',          type='Audio'),
      Input(name='In7',          type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='InSense1',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='InSense2',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='InSense3',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='InSense4',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='InSense5',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='InSense6',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='InSense7',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='InSense8',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='-6Db',
        low=0,
        high=1,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='Constant',
    type=43,
    height=2,
    inputs=[],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Value',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Unipolar',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='GainControl',
    type=44,
    height=2,
    inputs=[
      Input(name='Control',      type='Audio'),
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Shift',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='VocalFilter',
    type=45,
    height=5,
    inputs=[
      Input(name='In',           type='Audio'),
      Input(name='VowelSelectMod',type='Control'),
      Input(name='FrequencyMod', type='Control'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='LeftVowel',
        low=0,
        high=8,
        comment='vowel'
      ),
      Parameter(
        name='MiddleVowel',
        low=0,
        high=8,
        comment='vowel'
      ),
      Parameter(
        name='RightVowel',
        low=0,
        high=8,
        comment='vowel'
      ),
      Parameter(
        name='InAmplification',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='VowelSelect',
        low=0,
        high=127,
        comment='symeteric'
      ),
      Parameter(
        name='VowelSelectMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Frequency',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='FrequencyMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Resonance',
        low=0,
        high=127,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='AHD-Env',
    type=46,
    height=5,
    inputs=[
      Input(name='Trig',         type='Logic'),
      Input(name='AMod',         type='Control'),
      Input(name='HMod',         type='Control'),
      Input(name='DMod',         type='Control'),
      Input(name='In',           type='Audio'),
      Input(name='Amp',          type='Control'),
    ],
    outputs=[
      Output(name='Env',          type='Control'),
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='A',
        low=0,
        high=127,
        comment='adsrtime'
      ),
      Parameter(
        name='H',
        low=0,
        high=127,
        comment='adsrtime'
      ),
      Parameter(
        name='D',
        low=0,
        high=127,
        comment='adsrtime'
      ),
      Parameter(
        name='AMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='HMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='DMod',
        low=0,
        high=127,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='Pan',
    type=47,
    height=3,
    inputs=[
      Input(name='In',           type='Audio'),
      Input(name='Panmod',       type='Audio'),
    ],
    outputs=[
      Output(name='Outl',         type='Audio'),
      Output(name='Outr',         type='Audio'),
    ],
    parameters=[
      Parameter(
        name='PanMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Pan',
        low=0,
        high=127,
        comment='symetric'
      ),
    ],
    customs=[],
  ),
  Module(
    name='PortamentoA',
    type=48,
    height=2,
    inputs=[
      Input(name='In',           type='Control'),
      Input(name='On',           type='Logic'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Time',
        low=0,
        high=127,
        comment='adsrtime'
      ),
    ],
    customs=[],
  ),
  Module(
    name='FilterD',
    type=49,
    height=5,
    inputs=[
      Input(name='FreqMod',      type='Control'),
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Hp',           type='Audio'),
      Output(name='Bp',           type='Audio'),
      Output(name='Lp',           type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Freq',
        low=0,
        high=127,
        comment='filterfreq'
      ),
      Parameter(
        name='Kbt',
        low=0,
        high=127,
        comment='freqkbt'
      ),
      Parameter(
        name='Resonance',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Freqmod',
        low=0,
        high=127,
        comment=''
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=1,
        high=0,
        comment='freqdisplunits'
      ),
    ],
  ),
  Module(
    name='FilterC',
    type=50,
    height=4,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Lp',           type='Audio'),
      Output(name='Bp',           type='Audio'),
      Output(name='Hp',           type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Freq',
        low=0,
        high=127,
        comment='filterfreq'
      ),
      Parameter(
        name='Resonance',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='GainControl',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=1,
        high=0,
        comment='freqdisplunits'
      ),
    ],
  ),
  Module(
    name='FilterE',
    type=51,
    height=6,
    inputs=[
      Input(name='FreqMod1',     type='Audio'),
      Input(name='ResMod',       type='Audio'),
      Input(name='In',           type='Audio'),
      Input(name='FreqMod2',     type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='FilterType',
        low=0,
        high=3,
        comment='filtertype'
      ),
      Parameter(
        name='GainControl',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='FrequencyMod1',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Frequency',
        low=0,
        high=127,
        comment='filterfreq'
      ),
      Parameter(
        name='Kbt',
        low=0,
        high=127,
        comment='freqkbt'
      ),
      Parameter(
        name='ResonanceMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Resonance',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Slope',
        low=0,
        high=1,
        comment='filterslope2'
      ),
      Parameter(
        name='FrequencyMod2',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Bypass',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=1,
        high=0,
        comment='freqdisplunits'
      ),
    ],
  ),
  Module(
    name='Multi-Env',
    type=52,
    height=7,
    inputs=[
      Input(name='Gate',         type='Logic'),
      Input(name='In',           type='Audio'),
      Input(name='Amp',          type='Control'),
    ],
    outputs=[
      Output(name='Env',          type='Control'),
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Level1',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Level2',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Level3',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Level4',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Time1',
        low=0,
        high=127,
        comment='adsrtime'
      ),
      Parameter(
        name='Time2',
        low=0,
        high=127,
        comment='adsrtime'
      ),
      Parameter(
        name='Time3',
        low=0,
        high=127,
        comment='adsrtime'
      ),
      Parameter(
        name='Time4',
        low=0,
        high=127,
        comment='adsrtime'
      ),
      Parameter(
        name='Time5',
        low=0,
        high=127,
        comment='adsrtime'
      ),
      Parameter(
        name='Sustain',
        low=0,
        high=4,
        comment='0 ~ off, 4 ~ level 4'
      ),
      Parameter(
        name='Curve',
        low=0,
        high=2,
        comment='0 ~ bipolar, 1 ~ uni/exp, 2 ~ uni/lin'
      ),
    ],
    customs=[],
  ),
  Module(
    name='Sample&Hold',
    type=53,
    height=2,
    inputs=[
      Input(name='Trig',         type='Logic'),
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[],
    customs=[],
  ),
  Module(
    name='Quantizer',
    type=54,
    height=2,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Bits',
        low=0,
        high=12,
        comment='quantbits'
      ),
    ],
    customs=[],
  ),
  Module(
    name='InvLevShift',
    type=57,
    height=2,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Mode',
        low=0,
        high=2,
        comment='0 ~ bipolar, 1 ~ uni/neg, 2 ~ uni/pos'
      ),
      Parameter(
        name='Inv',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='DrumSynth',
    type=58,
    height=9,
    inputs=[
      Input(name='Trig',         type='Logic'),
      Input(name='Vel',          type='Control'),
      Input(name='Pitch',        type='Control'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Mtune',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Stune',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Mdecay',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Sdecay',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Mlevel',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Slevel',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='FilterFreq',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='FilterRes',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='FilterSweep',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='FilterDecay',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='FilterMode',
        low=0,
        high=2,
        comment='filtertype1'
      ),
      Parameter(
        name='Amount',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Decay',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Click',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Noise',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='CompareLev',
    type=59,
    height=2,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Level',
        low=0,
        high=127,
        comment='symetric'
      ),
    ],
    customs=[],
  ),
  Module(
    name='Clip',
    type=61,
    height=3,
    inputs=[
      Input(name='In',           type='Audio'),
      Input(name='Clip',         type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='ClipMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Clip',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Sym',
        low=0,
        high=1,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='Overdrive',
    type=62,
    height=3,
    inputs=[
      Input(name='OverdriveMod', type='Control'),
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='OverdriveMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Overdrive',
        low=0,
        high=127,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='KeyboardPatch',
    type=63,
    height=3,
    inputs=[],
    outputs=[
      Output(name='LatestNote',   type='Control'),
      Output(name='PatchGate',    type='Logic'),
      Output(name='LatestVelOn',  type='Control'),
      Output(name='LatestRelVel', type='Control'),
    ],
    parameters=[],
    customs=[],
  ),
  Module(
    name='NegEdgeDelay',
    type=64,
    height=2,
    inputs=[
      Input(name='In',           type='Logic'),
    ],
    outputs=[
      Output(name='Out',          type='Logic'),
    ],
    parameters=[
      Parameter(
        name='Time',
        low=0,
        high=127,
        comment='logictime'
      ),
    ],
    customs=[],
  ),
  Module(
    name='MIDIGlobal',
    type=65,
    height=2,
    inputs=[],
    outputs=[
      Output(name='Clock',        type='Logic'),
      Output(name='Sync',         type='Logic'),
      Output(name='Active',       type='Logic'),
    ],
    parameters=[],
    customs=[],
  ),
  Module(
    name='ControlMixer',
    type=66,
    height=2,
    inputs=[
      Input(name='In1',          type='Control'),
      Input(name='In2',          type='Control'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Inv1',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Level1',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Inv2',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Level2',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Mode',
        low=0,
        high=1,
        comment='0 ~ lin, 1 ~ exp'
      ),
    ],
    customs=[],
  ),
  Module(
    name='NoteDetect',
    type=67,
    height=2,
    inputs=[],
    outputs=[
      Output(name='Gate',         type='Logic'),
      Output(name='Velocity',     type='Control'),
      Output(name='Releasevelocity',type='Control'),
    ],
    parameters=[
      Parameter(
        name='Note',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
    ],
    customs=[],
  ),
  Module(
    name='ClkGen',
    type=68,
    height=3,
    inputs=[
      Input(name='Reset',        type='Logic'),
    ],
    outputs=[
      Output(name='24Pulses/Beat',type='Logic'),
      Output(name='4Pulses/Beat', type='Logic'),
      Output(name='Slv',          type='Slave'),
      Output(name='Sync',         type='Logic'),
    ],
    parameters=[
      Parameter(
        name='Rate',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='On/Off',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='ClkDiv',
    type=69,
    height=2,
    inputs=[
      Input(name='Clock',        type='Logic'),
      Input(name='Reset',        type='Logic'),
    ],
    outputs=[
      Output(name='Out',          type='Logic'),
    ],
    parameters=[
      Parameter(
        name='Divider',
        low=0,
        high=127,
        comment='logicdiv'
      ),
    ],
    customs=[],
  ),
  Module(
    name='LogicInv',
    type=70,
    height=2,
    inputs=[
      Input(name='In',           type='Logic'),
    ],
    outputs=[
      Output(name='Out',          type='Logic'),
    ],
    parameters=[],
    customs=[],
  ),
  Module(
    name='EnvFollower',
    type=71,
    height=3,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Attack',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Release',
        low=0,
        high=127,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='NoteScaler',
    type=72,
    height=2,
    inputs=[
      Input(name='In',           type='Control'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Transpose',
        low=0,
        high=127,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='LogicProc',
    type=73,
    height=2,
    inputs=[
      Input(name='In1',          type='Logic'),
      Input(name='In2',          type='Logic'),
    ],
    outputs=[
      Output(name='Out',          type='Logic'),
    ],
    parameters=[
      Parameter(
        name='Mode',
        low=0,
        high=2,
        comment='0 ~ and, 1 ~ or, 2 ~ xor'
      ),
    ],
    customs=[],
  ),
  Module(
    name='WaveWrap',
    type=74,
    height=3,
    inputs=[
      Input(name='In',           type='Audio'),
      Input(name='WrapMod',      type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='WrapMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Wrap',
        low=0,
        high=127,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='NoteQuant',
    type=75,
    height=2,
    inputs=[
      Input(name='In',           type='Control'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Range',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Notes',
        low=0,
        high=127,
        comment='0 ~ off'
      ),
    ],
    customs=[],
  ),
  Module(
    name='OnOff',
    type=76,
    height=2,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='On/Off',
        low=0,
        high=1,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='ClkDivFix',
    type=77,
    height=2,
    inputs=[
      Input(name='Reset',        type='Logic'),
      Input(name='Midiclock',    type='Logic'),
    ],
    outputs=[
      Output(name='16',           type='Logic'),
      Output(name='T8',           type='Logic'),
      Output(name='8',            type='Logic'),
    ],
    parameters=[],
    customs=[],
  ),
  Module(
    name='Delay',
    type=78,
    height=3,
    inputs=[
      Input(name='In',           type='Audio'),
      Input(name='Modulation',   type='Control'),
    ],
    outputs=[
      Output(name='2.65MsFixedDelay',type='Audio'),
      Output(name='VariableDelayOut',type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Modulation',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Time',
        low=0,
        high=127,
        comment='0 ~ 0 ms, 127 ~ 2.65 ms'
      ),
    ],
    customs=[],
  ),
  Module(
    name='4-1Switch',
    type=79,
    height=3,
    inputs=[
      Input(name='In1',          type='Audio'),
      Input(name='In2',          type='Audio'),
      Input(name='In3',          type='Audio'),
      Input(name='In4',          type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='In',
        low=0,
        high=3,
        comment=''
      ),
      Parameter(
        name='Level1',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Level2',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Level3',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Level4',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='LFOSlvA',
    type=80,
    height=4,
    inputs=[
      Input(name='Master',       type='Slave'),
      Input(name='Reset',        type='Logic'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Rate',
        low=0,
        high=127,
        comment='lfoslvrate'
      ),
      Parameter(
        name='Phase',
        low=0,
        high=127,
        comment='phase'
      ),
      Parameter(
        name='Waveform',
        low=0,
        high=4,
        comment='lfoshape'
      ),
      Parameter(
        name='Mono',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=1,
        high=0,
        comment='freqdisplunitslfo'
      ),
    ],
  ),
  Module(
    name='Amplifier',
    type=81,
    height=2,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Gain',
        low=0,
        high=127,
        comment='ampgain'
      ),
    ],
    customs=[],
  ),
  Module(
    name='Diode',
    type=82,
    height=2,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Mode',
        low=0,
        high=2,
        comment='0 ~ off, 1 ~ half wave, 2 ~ full wave'
      ),
    ],
    customs=[],
  ),
  Module(
    name='Shaper',
    type=83,
    height=2,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Mode',
        low=0,
        high=4,
        comment='0 ~ log2, 1 ~ log1, 2 ~ lin, 3 ~ exp1, 4 ~ exp2'
      ),
    ],
    customs=[],
  ),
  Module(
    name='AD-Env',
    type=84,
    height=3,
    inputs=[
      Input(name='Trigger',      type='Logic'),
      Input(name='In',           type='Audio'),
      Input(name='Amp',          type='Control'),
    ],
    outputs=[
      Output(name='Envelope',     type='Control'),
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Attack',
        low=0,
        high=127,
        comment='adsrtime'
      ),
      Parameter(
        name='Decay',
        low=0,
        high=127,
        comment='adsrtime'
      ),
      Parameter(
        name='Gate',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='OscSlvFM',
    type=85,
    height=3,
    inputs=[
      Input(name='Master',       type='Slave'),
      Input(name='Fmb',          type='Audio'),
      Input(name='Sync',         type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Detune',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Fine',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='-3Oct',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Fmb',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=1,
        high=0,
        comment='freqdisplunits'
      ),
    ],
  ),
  Module(
    name='FilterA',
    type=86,
    height=2,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Frequency',
        low=0,
        high=127,
        comment='filterfreqAB'
      ),
    ],
    customs=[],
  ),
  Module(
    name='FilterB',
    type=87,
    height=2,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Frequency',
        low=0,
        high=127,
        comment='filterfreqAB'
      ),
    ],
    customs=[],
  ),
  Module(
    name='1-4Switch',
    type=88,
    height=3,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out1',         type='Audio'),
      Output(name='Out2',         type='Audio'),
      Output(name='Out3',         type='Audio'),
      Output(name='Out4',         type='Audio'),
    ],
    parameters=[
      Parameter(
        name='In',
        low=0,
        high=3,
        comment='0 ~ out1, 3 ~ out4'
      ),
      Parameter(
        name='Level',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='CompareAB',
    type=89,
    height=2,
    inputs=[
      Input(name='A',            type='Control'),
      Input(name='B',            type='Control'),
    ],
    outputs=[
      Output(name='A>=B',         type='Logic'),
    ],
    parameters=[],
    customs=[],
  ),
  Module(
    name='NoteSeqB',
    type=90,
    height=9,
    inputs=[
      Input(name='Clock',        type='Logic'),
      Input(name='Reset',        type='Logic'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
      Output(name='Sync',         type='Logic'),
      Output(name='Link',         type='Logic'),
      Output(name='Gclk',         type='Logic'),
    ],
    parameters=[
      Parameter(
        name='Note1',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='Note2',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='Note3',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='Note4',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='Note5',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='Note6',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='Note7',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='Note8',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='Note9',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='Note10',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='Note11',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='Note12',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='Note13',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='Note14',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='Note15',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='Note16',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='Step',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Currentstep',
        low=0,
        high=16,
        comment='editpos'
      ),
      Parameter(
        name='Record',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Play',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Loop',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[
      Custom(
        name='Zoomfactor',
        low=6,
        high=1,
        comment=''
      ),
      Custom(
        name='Sliderposition',
        low=117,
        high=6,
        comment=''
      ),
    ],
  ),
  Module(
    name='CtrlSeq',
    type=91,
    height=7,
    inputs=[
      Input(name='Clock',        type='Logic'),
      Input(name='Reset',        type='Logic'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
      Output(name='Sync',         type='Logic'),
      Output(name='Link',         type='Logic'),
    ],
    parameters=[
      Parameter(
        name='Ctrl1',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Ctrl2',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Ctrl3',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Ctrl4',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Ctrl5',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Ctrl6',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Ctrl7',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Ctrl8',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Ctrl9',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Ctrl10',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Ctrl11',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Ctrl12',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Ctrl13',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Ctrl14',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Ctrl15',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Ctrl16',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Step',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Uni',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Loop',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='FilterF',
    type=92,
    height=6,
    inputs=[
      Input(name='FreqMod1',     type='Control'),
      Input(name='FreqMod2',     type='Control'),
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Frequency',
        low=0,
        high=127,
        comment='filterfreq'
      ),
      Parameter(
        name='Kbt',
        low=0,
        high=127,
        comment='freqkbt'
      ),
      Parameter(
        name='Resonance',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='FreqMod1',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='FreqMod2',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Slope',
        low=0,
        high=2,
        comment='filtertype1'
      ),
      Parameter(
        name='Bypass',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=1,
        high=0,
        comment='freqdisplunits'
      ),
    ],
  ),
  Module(
    name='StereoChorus',
    type=94,
    height=3,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Outleft',      type='Audio'),
      Output(name='Outright',     type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Detune',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Amount',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Bypass',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='PercOsc',
    type=95,
    height=4,
    inputs=[
      Input(name='Trig',         type='Audio'),
      Input(name='Amp',          type='Audio'),
      Input(name='Pitchmod',     type='Control'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Pitch',
        low=0,
        high=127,
        comment='0 ~ 8.18 Hz, 127 ~ 12.54 kHz'
      ),
      Parameter(
        name='Click',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Decay',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Punch',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Pitchmod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Pitchfine',
        low=0,
        high=127,
        comment='freqfine'
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=1,
        high=0,
        comment='freqdisplunits'
      ),
    ],
  ),
  Module(
    name='FormantOsc',
    type=96,
    height=4,
    inputs=[
      Input(name='PitchMod1',    type='Control'),
      Input(name='PitchMod2',    type='Control'),
      Input(name='Timbre',       type='Control'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
      Output(name='Slave',        type='Slave'),
    ],
    parameters=[
      Parameter(
        name='Pitch',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='PitchFine',
        low=0,
        high=127,
        comment='freqfine'
      ),
      Parameter(
        name='Kbt',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Timbre',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='PitchMod1',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='PitchMod2',
        low=0,
        high=127,
        comment=''
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=1,
        high=0,
        comment='freqdisplunits'
      ),
    ],
  ),
  Module(
    name='MasterOsc',
    type=97,
    height=3,
    inputs=[
      Input(name='PitchMod1',    type='Control'),
      Input(name='PitchMod2',    type='Control'),
    ],
    outputs=[
      Output(name='Slave',        type='Slave'),
    ],
    parameters=[
      Parameter(
        name='Pitch',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='PitchFine',
        low=0,
        high=127,
        comment='freqfine'
      ),
      Parameter(
        name='Kbt',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='PitchMod1',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='PitchMod2',
        low=0,
        high=127,
        comment=''
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=1,
        high=0,
        comment='freqdisplunits'
      ),
    ],
  ),
  Module(
    name='KeyQuant',
    type=98,
    height=4,
    inputs=[
      Input(name='In',           type='Control'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Range',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Cont',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='E',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='F',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='F#',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='G',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='G#',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='A',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Bb',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='B',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='C',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='C#',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='D',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='D#',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='PatternGen',
    type=99,
    height=4,
    inputs=[
      Input(name='Clock',        type='Logic'),
      Input(name='Reset',        type='Logic'),
      Input(name='Pattern&Bank', type='Control'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Pattern',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Bank',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='LowDelta',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Step',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Mono',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='Keyboard',
    type=100,
    height=3,
    inputs=[
      Input(name='Note',         type='Control'),
      Input(name='Gate',         type='Logic'),
      Input(name='Vel',          type='Control'),
    ],
    outputs=[
      Output(name='Note',         type='Control'),
      Output(name='Gate',         type='Logic'),
      Output(name='Vel',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Lower',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='Upper',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
    ],
    customs=[],
  ),
  Module(
    name='Phaser',
    type=102,
    height=7,
    inputs=[
      Input(name='In',           type='Audio'),
      Input(name='CenterFreqMod',type='Control'),
      Input(name='SpreadMod',    type='Control'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Rate',
        low=0,
        high=127,
        comment='0 ~ 62.9 s, 127 ~ 24.4 hHz'
      ),
      Parameter(
        name='Lfo',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='CenterFreqMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='CenterFreq',
        low=0,
        high=127,
        comment='0 ~ 100 Hz, 127 ~ 16 kHz'
      ),
      Parameter(
        name='SpreadMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Feedback',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Peaks',
        low=0,
        high=5,
        comment='0 ~ 1 peak, 5 ~ 6 peaks'
      ),
      Parameter(
        name='Spread',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Bypass',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Depth',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Inlevel',
        low=0,
        high=127,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='EqMid',
    type=103,
    height=4,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Freq',
        low=0,
        high=127,
        comment='eqfreq'
      ),
      Parameter(
        name='Gain',
        low=0,
        high=127,
        comment='eqgain'
      ),
      Parameter(
        name='Bandwidth',
        low=0,
        high=127,
        comment='0 ~ 2 oct, 64 ~ 1 oct, 127 ~ 0.02 oct'
      ),
      Parameter(
        name='Bypass',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='InLevel',
        low=0,
        high=127,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='EqShelving',
    type=104,
    height=4,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Freq',
        low=0,
        high=127,
        comment='eqfreq'
      ),
      Parameter(
        name='Gain',
        low=0,
        high=127,
        comment='eqgain'
      ),
      Parameter(
        name='Mode',
        low=0,
        high=1,
        comment='0 ~ low, 1 ~ high'
      ),
      Parameter(
        name='Bypass',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='InLevel',
        low=0,
        high=127,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='Expander',
    type=105,
    height=7,
    inputs=[
      Input(name='InLeft',       type='Audio'),
      Input(name='InRight',      type='Audio'),
      Input(name='Sidechain',    type='Audio'),
    ],
    outputs=[
      Output(name='OutLeft',      type='Audio'),
      Output(name='OutRight',     type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Attack',
        low=0,
        high=127,
        comment='companderattack'
      ),
      Parameter(
        name='Release',
        low=0,
        high=127,
        comment='companderrelease'
      ),
      Parameter(
        name='Treshold',
        low=0,
        high=84,
        comment='compandertreshold'
      ),
      Parameter(
        name='Ratio',
        low=0,
        high=66,
        comment='companderratio'
      ),
      Parameter(
        name='Gate',
        low=0,
        high=72,
        comment='compandergate'
      ),
      Parameter(
        name='Hold',
        low=0,
        high=127,
        comment='companderhold'
      ),
      Parameter(
        name='SidechainActivation',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='SidechainMonitor',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Bypass',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='OscSineBank',
    type=106,
    height=10,
    inputs=[
      Input(name='Master',       type='Slave'),
      Input(name='Mixin',        type='Audio'),
      Input(name='Sync',         type='Audio'),
      Input(name='Osc1Am',       type='Audio'),
      Input(name='Osc2Am',       type='Audio'),
      Input(name='Osc3Am',       type='Audio'),
      Input(name='Osc4Am',       type='Audio'),
      Input(name='Osc5Am',       type='Audio'),
      Input(name='Osc6Am',       type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Osc1Coarse',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Osc1Fine',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Osc1Level',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Osc2Coarse',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Osc2Fine',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Osc2Level',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Osc3Coarse',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Osc3Fine',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Osc3Level',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Osc4Coarse',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Osc4Fine',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Osc4Level',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Osc5Coarse',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Osc5Fine',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Osc5Level',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Osc6Coarse',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Osc6Fine',
        low=0,
        high=127,
        comment='symetric'
      ),
      Parameter(
        name='Osc6Level',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Osc1Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Osc2Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Osc3Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Osc4Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Osc5Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Osc6Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='SpectralOsc',
    type=107,
    height=5,
    inputs=[
      Input(name='Fma',          type='Audio'),
      Input(name='PitchMod1',    type='Control'),
      Input(name='PitchMod2',    type='Control'),
      Input(name='SpectralShapeMod',type='Control'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
      Output(name='Slave',        type='Slave'),
    ],
    parameters=[
      Parameter(
        name='FreqCoarse',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='FreqFine',
        low=0,
        high=127,
        comment='freqfine'
      ),
      Parameter(
        name='SpectralShape',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Partials',
        low=0,
        high=1,
        comment='0 ~ odd, 1 ~ all'
      ),
      Parameter(
        name='PitchMod1',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='PitchMod2',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Fma',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='SpectralShapeMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='Kbt',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='Mute',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[
      Custom(
        name='FreqDisplayUnits',
        low=1,
        high=0,
        comment='freqdisplunits'
      ),
    ],
  ),
  Module(
    name='Vocoder',
    type=108,
    height=8,
    inputs=[
      Input(name='Control',      type='Audio'),
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Band1',
        low=0,
        high=16,
        comment='vocoband'
      ),
      Parameter(
        name='Band2',
        low=0,
        high=16,
        comment='vocoband'
      ),
      Parameter(
        name='Band3',
        low=0,
        high=16,
        comment='vocoband'
      ),
      Parameter(
        name='Band4',
        low=0,
        high=16,
        comment='vocoband'
      ),
      Parameter(
        name='Band5',
        low=0,
        high=16,
        comment='vocoband'
      ),
      Parameter(
        name='Band6',
        low=0,
        high=16,
        comment='vocoband'
      ),
      Parameter(
        name='Band7',
        low=0,
        high=16,
        comment='vocoband'
      ),
      Parameter(
        name='Band8',
        low=0,
        high=16,
        comment='vocoband'
      ),
      Parameter(
        name='Band9',
        low=0,
        high=16,
        comment='vocoband'
      ),
      Parameter(
        name='Band10',
        low=0,
        high=16,
        comment='vocoband'
      ),
      Parameter(
        name='Band11',
        low=0,
        high=16,
        comment='vocoband'
      ),
      Parameter(
        name='Band12',
        low=0,
        high=16,
        comment='vocoband'
      ),
      Parameter(
        name='Band13',
        low=0,
        high=16,
        comment='vocoband'
      ),
      Parameter(
        name='Band14',
        low=0,
        high=16,
        comment='vocoband'
      ),
      Parameter(
        name='Band15',
        low=0,
        high=16,
        comment='vocoband'
      ),
      Parameter(
        name='Band16',
        low=0,
        high=16,
        comment='vocoband'
      ),
      Parameter(
        name='Outgain',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='HighFreqEmphasis',
        low=0,
        high=1,
        comment=''
      ),
      Parameter(
        name='Monitor',
        low=0,
        high=1,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='RandomGen',
    type=110,
    height=2,
    inputs=[
      Input(name='Master',       type='Slave'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='Rate',
        low=0,
        high=127,
        comment='lfoslvrate'
      ),
    ],
    customs=[],
  ),
  Module(
    name='LevMult',
    type=111,
    height=2,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Multiplier',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Unipolar',
        low=0,
        high=1,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='LevAdd',
    type=112,
    height=2,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Offset',
        low=0,
        high=127,
        comment='unibi'
      ),
      Parameter(
        name='Unipolar',
        low=0,
        high=1,
        comment=''
      ),
    ],
    customs=[],
  ),
  Module(
    name='1to2Fade',
    type=113,
    height=2,
    inputs=[
      Input(name='In',           type='Audio'),
    ],
    outputs=[
      Output(name='Out1',         type='Audio'),
      Output(name='Out2',         type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Fade',
        low=0,
        high=127,
        comment='symetric'
      ),
    ],
    customs=[],
  ),
  Module(
    name='2to1Fade',
    type=114,
    height=2,
    inputs=[
      Input(name='In1',          type='Audio'),
      Input(name='In2',          type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='Fade',
        low=0,
        high=127,
        comment='symetric'
      ),
    ],
    customs=[],
  ),
  Module(
    name='NoteVelScal',
    type=115,
    height=4,
    inputs=[
      Input(name='Velocity',     type='Control'),
      Input(name='Note',         type='Control'),
    ],
    outputs=[
      Output(name='Out',          type='Control'),
    ],
    parameters=[
      Parameter(
        name='VelocitySensitivity',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='LeftGain',
        low=0,
        high=48,
        comment='velscalgain'
      ),
      Parameter(
        name='Breakpoint',
        low=0,
        high=127,
        comment='freqcoarse'
      ),
      Parameter(
        name='RightGain',
        low=0,
        high=48,
        comment='velscalgain'
      ),
    ],
    customs=[],
  ),
  Module(
    name='RingMod',
    type=117,
    height=3,
    inputs=[
      Input(name='In',           type='Audio'),
      Input(name='Modulation',   type='Audio'),
      Input(name='Modulationdepth',type='Audio'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='RingmodDepthMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='RingmodDepth',
        low=0,
        high=127,
        comment='0 ~ 0, 64 ~ AM, 127 ~ RM'
      ),
    ],
    customs=[],
  ),
  Module(
    name='Digitizer',
    type=118,
    height=3,
    inputs=[
      Input(name='In',           type='Audio'),
      Input(name='SampleRateMod',type='Control'),
    ],
    outputs=[
      Output(name='Out',          type='Audio'),
    ],
    parameters=[
      Parameter(
        name='QuantBits',
        low=0,
        high=11,
        comment='quantbits'
      ),
      Parameter(
        name='SampleRate',
        low=0,
        high=127,
        comment='0 ~ 34.65 Hz, 127 ~ 50.18 kHz'
      ),
      Parameter(
        name='SampleRateMod',
        low=0,
        high=127,
        comment=''
      ),
      Parameter(
        name='QuantOff',
        low=0,
        high=1,
        comment='onoff'
      ),
      Parameter(
        name='SamplingOff',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
  Module(
    name='PolyAreaIn',
    type=127,
    height=2,
    inputs=[],
    outputs=[
      Output(name='Left',         type='Audio'),
      Output(name='Right',        type='Audio'),
    ],
    parameters=[
      Parameter(
        name='+6Db',
        low=0,
        high=1,
        comment='onoff'
      ),
    ],
    customs=[],
  ),
]

fromtype = {}
fromname = {}
modulemap = Struct()
for module in modules:
  fromname[module.name] = module
  fromtype[module.type] = module
  name = module.name.replace('-','_').replace('&','n').replace(' ','_')
  setattr(modulemap, name, module)

